---
title: "Final Project"
author: "Semin Seo"
date: "`r Sys.Date()`"
documentclass: article
geometry: margin=1in
fontsize: 11pt
output:
  pdf_document:
    toc: false
    df_print: kable
    fig_caption: false
    number_sections: false
    dev: pdf
    highlight: tango
  html_document:
    theme: default
    self_contained: true
    toc: false
    df_print: kable
    fig_caption: false
    number_sections: false
    smart: true
    dev: svg
    
---

```{r setup, include = FALSE}
# DO NOT ALTER THIS CHUNK
knitr::opts_chunk$set(
  echo = TRUE,
  eval = TRUE,
  fig.width = 5,
  fig.asp = 0.618,
  out.width = "70%",
  dpi = 120,
  fig.align = "center",
  cache = FALSE
)
# Cost function for cross validation
cost <- function(obs, pred) {
  outcome <- pred > 0.5
  return(1 - (sum(obs == outcome) / length(obs)))
}
# Load required packages
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(ggmosaic))
suppressPackageStartupMessages(library(modelr))
suppressPackageStartupMessages(library(boot))
```

# Load the dataset
```{r}
library(tidyr)
library(ggplot2)
library(ggmosaic)
library(dplyr)
Sleep_health_and_lifestyle_dataset <- read_csv("Sleep_health_and_lifestyle_dataset.csv")
```
#Convert Data Name
```{r}
Sleep_health_and_lifestyle_dataset_renamed <- Sleep_health_and_lifestyle_dataset %>%
  rename( Duration = 'Sleep Duration',
          Stress = 'Stress Level',
          Physical = 'Physical Activity Level' ,
          Quality = 'Quality of Sleep' ,
          BMI= 'BMI Category' ,
          BPressure = 'Blood Pressure' ,
          HRate = 'Heart Rate' ,
          DSteps = 'Daily Steps' ,
          Disorder = 'Sleep Disorder' )
```
```{r}
Sleep_health_and_lifestyle_dataset_renamed$BMI[Sleep_health_and_lifestyle_dataset_renamed$BMI == "Overweight"] <- "Fat"
Sleep_health_and_lifestyle_dataset_renamed$BMI[Sleep_health_and_lifestyle_dataset_renamed$BMI == "Obese"] <- "Fat"
Sleep_health_and_lifestyle_dataset_renamed$BMI[Sleep_health_and_lifestyle_dataset_renamed$BMI == "Normal Weight"] <- "Normal"
```

# Explore dataset
```{r}
str(Sleep_health_and_lifestyle_dataset)
```
```{r}
head(Sleep_health_and_lifestyle_dataset)
```
```{r}
tail(Sleep_health_and_lifestyle_dataset)
```
# Check summary


```{r}
summary(Sleep_health_and_lifestyle_dataset_renamed)
```
```{r}
Sleep_health_and_lifestyle_dataset_renamed %>%
  summarize(
    standard_deviation = sd(HRate)
    
  )
```
# Visualizing data
## Histogram
```{r}
Sleep_health_and_lifestyle_dataset_renamed %>%
  ggplot() +
    geom_histogram(mapping = aes(x = HRate)) +
    labs(title = "Count of Heart Rate", x = "Heart rate")
```

## Box plot

```{r}
Sleep_health_and_lifestyle_dataset_renamed %>%
  ggplot() +
    geom_boxplot(mapping = aes(x = HRate)) +
    labs(title = "Boxplot of Individual Heart Rate", x = "Heart rate")
```
## Violin plot
```{r}
Sleep_health_and_lifestyle_dataset_renamed %>%
  ggplot() +
    geom_violin(mapping = aes(x = HRate, y ="")) +
    labs(title = "Violin of Individual Heart rate", x = "Heart rate", y = "y")
```
```{r}
Sleep_health_and_lifestyle_dataset_renamed %>%
  ggplot() +
  geom_bin2d(mapping = aes(x = HRate, y = Duration)) +
  labs(title = "HRate and Duration ",x = "Heart Rate",y = "Duration") + scale_fill_viridis_c(trans = "log")
```

## Bar Graph
```{r}
Sleep_health_and_lifestyle_dataset_renamed %>%
  ggplot() +
    geom_bar(mapping = aes(x = BMI)) +
    labs(title = "BMI Count", x = "BMI")
```

## Box plot
```{r}
Sleep_health_and_lifestyle_dataset_renamed %>%
  ggplot() +
    geom_boxplot(mapping = aes(x = BMI, y = Duration)) +
    labs(title = "Relationship between BMI and Duration", x = "BMI")
```
## Violin plot
```{r}
Sleep_health_and_lifestyle_dataset_renamed %>%
  ggplot() +
    geom_violin(mapping = aes(x = BMI, y = Duration)) +
    labs(title = "Relationship between BMI and Duration", x = "bmi", y = "Duration")
```

#Scatter plot_Duration and Heart Rate

```{r}
Sleep_health_and_lifestyle_dataset_renamed    %>% 
ggplot()    +
geom_point(mapping = aes(x = BMI, y = Duration))    + 
labs(
title = "Scatter plot of Duration and Heart Rate", 
x = "BMI",
y = "Duration" 
)
```




