---
title: "Final Project"
author: "Group 1"
date: "`r Sys.Date()`"
documentclass: article
geometry: margin=1in
fontsize: 11pt
output:
  pdf_document:
    toc: false
    df_print: kable
    fig_caption: false
    number_sections: false
    dev: pdf
    highlight: tango
  html_document:
    theme: default
    self_contained: true
    toc: false
    df_print: kable
    fig_caption: false
    number_sections: false
    smart: true
    dev: svg
    
---

```{r setup, include = FALSE}
# DO NOT ALTER THIS CHUNK
knitr::opts_chunk$set(
  echo = TRUE,
  eval = TRUE,
  fig.width = 5,
  fig.asp = 0.618,
  out.width = "70%",
  dpi = 120,
  fig.align = "center",
  cache = FALSE
)
# Cost function for cross validation
cost <- function(obs, pred) {
  outcome <- pred > 0.5
  return(1 - (sum(obs == outcome) / length(obs)))
}
# Load required packages
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(ggmosaic))
suppressPackageStartupMessages(library(modelr))
suppressPackageStartupMessages(library(boot))
```


```{r}
library(tidyr)
library(ggplot2)
library(ggmosaic)
library(dplyr)
library(infer)
Sleep_health_and_lifestyle_dataset <- read_csv("Sleep_health_and_lifestyle_dataset.csv")
```


```{r}
Sleep_health_and_lifestyle_dataset_renamed <- Sleep_health_and_lifestyle_dataset %>%
  rename( Duration = 'Sleep Duration',
          Stress = 'Stress Level',
          Physical = 'Physical Activity Level' ,
          Quality = 'Quality of Sleep' ,
          BMI= 'BMI Category' ,
          BPressure = 'Blood Pressure' ,
          HRate = 'Heart Rate' ,
          DSteps = 'Daily Steps' ,
          Disorder = 'Sleep Disorder' )
```



```{r}
names(Sleep_health_and_lifestyle_dataset_renamed)
```

```{r}
Sleep_health_and_lifestyle_dataset_renamed$BMI[Sleep_health_and_lifestyle_dataset_renamed$BMI == "Overweight"] <- "High"
Sleep_health_and_lifestyle_dataset_renamed$BMI[Sleep_health_and_lifestyle_dataset_renamed$BMI == "Obese"] <- "High"
Sleep_health_and_lifestyle_dataset_renamed$BMI[Sleep_health_and_lifestyle_dataset_renamed$BMI == "Normal Weight"] <- "Normal"
```



```{r}
Sleep_health_and_lifestyle_dataset_renamed %>%
  filter(BMI == "Normal" | BMI == "High") %>%
  ggplot() +
  geom_histogram( 
    mapping = aes(x = Duration, fill = BMI), 
    position = "identity",
alpha = 0.5
  )
```


```{r}
Sleep_health_and_lifestyle_dataset_renamed %>%
  filter(BMI == "Normal" | BMI == "High") %>%
  ggplot() +
  geom_histogram( 
    mapping = aes(x = Duration, y= ..density.., fill = BMI), 
    position = "identity",
alpha = 0.5
  )
```


```{r}
Sleep_health_and_lifestyle_dataset_renamed %>%
  filter(BMI == "Normal" | BMI == "High") %>%
  ggplot() +
  geom_density( 
    mapping = aes(x = Duration, fill = BMI), 
    position = "identity",
alpha = 0.5
  )
```


```{r}
Sleep_health_and_lifestyle_dataset_renamed %>%
summarize(
mean = mean(Duration),
median = median(Duration), 
standard_deviation = sd(Duration), 
minimum = min(Duration),
maximum = max(Duration)
)
```




```{r}
Model <- lm(Duration ~ BMI, data = Sleep_health_and_lifestyle_dataset_renamed)
Simulation_results <-
  Sleep_health_and_lifestyle_dataset_renamed %>%
  specify(Duration ~ BMI) %>%
  hypothesize(null = "independence") %>%
  generate(reps = 1000, type = "permute") %>% 
  calculate(stat = "diff in means", order = c("Normal", "High"))
```


```{r}
Shl_obs_stat <-
  Sleep_health_and_lifestyle_dataset_renamed %>%
  specify(formula = Duration ~ BMI) %>%
  calculate(stat = "diff in means", order = c("Normal","High"))
```

```{r}
Shl_null <- Sleep_health_and_lifestyle_dataset_renamed %>%
  specify(Duration ~ BMI) %>%
  hypothesize(null = "independence") %>%
  generate(reps = 1000, type = "permute")
```


```{r}
Shl_null %>%
  get_p_value(obs_stat = Shl_obs_stat, direction = "right")
```



```{r}
Shl_null %>% get_p_value(obs_stat = Shl_obs_stat, direction = "right")
p_value <- Shl_null %>% get_p_value(obs_stat = Shl_obs_stat, direction = "right")
```

```{r}
Sleep_health_and_lifestyle_dataset_renamed %>%
  filter(BMI == "Normal" | BMI == "High") %>%
  ggplot() +
  geom_density(mapping = aes(x = Duration, fill = BMI), position = "identity", alpha = 0.5) +
  geom_text(aes(x = Inf, y = Inf, label = paste("p-value =", round(p_value, 3))),
            hjust = 1, vjust = 1, color = "red") +
  labs(title = "Duration vs. BMI Density Plot",
       x = "Duration",
       y = "Density") +
  theme_minimal()
```





